<?php
declare(strict_types=1);

namespace Plaisio;

/**
 * Class for holding all constants generated by PhpStratum.
 */
class C
{
  //--------------------------------------------------------------------------------------------------------------------
  /**
   * @setbased.stratum.constants
   *
   * Below this doc block constants will be inserted by PhpStratum.
   */
  const CMP_ID_ABC                    = 2;
  const CMP_ID_SYS                    = 1;
  const LGR_ID_GRANTED                = 1;
  const LGR_ID_NOT_GRANTED            = 4;
  const LGR_ID_TO_MANY_WRONG_PASSWORD = 3;
  const LGR_ID_WRONG_PASSWORD         = 2;

  //--------------------------------------------------------------------------------------------------------------------
}

//----------------------------------------------------------------------------------------------------------------------
