<?php
declare(strict_types=1);

namespace Plaisio\Login\Test;

use Plaisio\CompanyResolver\CompanyResolver;
use Plaisio\PlaisioKernel;
use Plaisio\Request\CoreRequest;
use Plaisio\Request\Request;
use Plaisio\Session\Session;
use SetBased\Stratum\MySql\MySqlDefaultConnector;

/**
 * Kernel for testing purposes.
 */
class TestKernel extends PlaisioKernel
{
  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the helper object for deriving the company.
   *
   * @return CompanyResolver
   */
  protected function getCompany(): CompanyResolver
  {
    return new TestCompanyResolver();
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the data layer generated by PhpStratum.
   *
   * @return Object
   */
  protected function getDL(): object
  {
    $connector = new MySqlDefaultConnector('127.0.0.1', 'test', 'test', 'test');
    $dl        = new TestDataLayer($connector);
    $dl->connect();
    $dl->begin();

    return $dl;
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the helper object for providing information about the HTTP request.
   *
   * @return Request
   */
  protected function getRequest(): Request
  {
    $request = new CoreRequest($_SERVER, $_COOKIE);
    $request->validate();

    return $request;
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the helper object for session management.
   *
   * @return Session
   */
  protected function getSession(): Session
  {
    return new TestSession();
  }

  //--------------------------------------------------------------------------------------------------------------------
}

//----------------------------------------------------------------------------------------------------------------------
